In [1]:
import numpy as np


In [2]:
n1=np.array([45,47,49,70])

In [3]:
print(n1)
n1.dtype

[45 47 49 70]


dtype('int32')

In [4]:
n2=np.array([[1,3,5,7],[2,4,6,8]])

In [5]:
print(n2)

[[1 3 5 7]
 [2 4 6 8]]


In [6]:
n3=np.array([[2,4,6,8],[1,3,5,7]])
n3

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [7]:
multi=n2*n3


In [8]:
print(multi)

[[ 2 12 30 56]
 [ 2 12 30 56]]


In [9]:
type(n1)
type(n2)
type(n3)


numpy.ndarray

In [10]:
n0=np.zeros([4,4])

In [11]:

print(n0)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
nfull=np.full((4,4), 5)

In [13]:
nfull

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [14]:
n_arange=np.arange(20,28)

In [15]:
n_arange

array([20, 21, 22, 23, 24, 25, 26, 27])

In [16]:
n_arange1=np.arange(10,101,5)

In [17]:
n_arange1

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [18]:
n_rand1=np.random.randint(20,40,7)
n_rand1

array([28, 28, 27, 32, 21, 22, 35])

In [19]:
# random function not operate for float type data
n_rand2=np.random.randf(20,40,6)
n_rand2

AttributeError: module 'numpy.random' has no attribute 'randf'

In [ ]:
n0=np.zeros([4,4])
print("Shape is") # syntex used to comment out shape(not neccesry)
n0.shape

In [ ]:
nfull=n0=np.full((4,6), 5)
print(nfull)
print("Shape is")
nfull.shape

In [20]:
n3=np.array([[2,4,6,8],[1,3,5,7]])
print(n2)

print("Shape is")
n2.shape

[[1 3 5 7]
 [2 4 6 8]]
Shape is


(2, 4)

In [ ]:
n3.shape=(4,2) # change the shape of array
print(n3)

print("Shape is")
n3.shape

In [ ]:
n3.shape=(8,1)
print(n3)

print("Shape is")
n3.shape

In [ ]:
n3.shape=(1,8)
print(n3)

print("Shape is")
n3.shape

In [ ]:
n3.shape=(2,2) # this trasformation not possible (only row & column interchaged when numbers are equal)

In [ ]:
import numpy as np

In [ ]:
n2=np.array([[11,3,5,7],[2,4,6,8]])
n3=np.array([[12,4,6,8],[1,3,5,7]])
nr=np.array([[9,8,6,7],[5,4,3,2]])

In [ ]:
np.vstack((n2,n3,nr))              #vertical Stacking

In [ ]:
np.hstack((n2,n3,nr))              #Horizontal Stacking

In [ ]:
np.column_stack((n2,n3,nr))              #column  Stacking

In [ ]:
n2=np.array([[11,3,5,7],[2,4,6,8]])
n3=np.array([[12,4,6,8],[1,3,5,7]])
nr=np.array([[9,8,6,7],[5,4,3,2]])

In [ ]:
np.intersect1d(n2,n3)    #set intersection

In [ ]:
np.intersect1d(nr,n2)

In [ ]:
np.intersect1d(nr,n3)

In [ ]:
np.setdiff1d(n2,n3)   #differance in n2 -n3

In [ ]:
np.setdiff1d(n3,n2)    #differance in n3 -n2

In [ ]:
np.setdiff1d(nr,n3)     #differance in nr -n3

In [ ]:
np.setdiff1d(n3,nr)   #differance in n3 -nr

In [ ]:
np.setdiff1d(n2,nr)   #differance in n2 -nr

In [ ]:
np.setdiff1d(nr,n2)     #differance in nr -n3